import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section>
          <ul>
            {posts.map((post) => {
              return (
                <li key={post.id}>
                  <Link href={`blog/${post.id}`}>{post.title}</Link>
                </li>
              );
            })}
          </ul>
        </section>
      </main>
    </>
  );
}

// get datas from API
export async function getServerSideProps(context) {
  const posts = await fetch(
    "https://jsonplaceholder.typicode.com/posts?_limit=4"
  ).then((response) => response.json());

  return {
    props: {
      posts,
    },
  };
}
